// src/app/components/KnowledgePage.tsx
import React, { useState } from 'react';
import { Search, FileText, Star, BookOpen } from 'lucide-react';
import { KNOWLEDGE_ARTICLES, KNOWLEDGE_SECTIONS, KNOWLEDGE_CATEGORIES, KnowledgeArticle } from '../data/knowledge';

interface Props {
  favorites: Set<string>;
  onToggleFavorite: (id: string) => void;
  onOpenArticle: (id: string) => void;
}

const COLOR_MAP: Record<string, string> = {
  indigo:  'bg-indigo-50 text-indigo-600 border-indigo-100',
  sky:     'bg-sky-50 text-sky-600 border-sky-100',
  emerald: 'bg-emerald-50 text-emerald-600 border-emerald-100',
  teal:    'bg-teal-50 text-teal-600 border-teal-100',
};

const CAT_COLOR: Record<string, string> = {
  'ГИА':          'bg-indigo-100 text-indigo-700',
  'Методология':  'bg-sky-100 text-sky-700',
  'Аккредитация': 'bg-emerald-100 text-emerald-700',
  'Практика':     'bg-teal-100 text-teal-700',
};

const SECTION_ICON: Record<string, string> = {
  'Помощь для РОПа':      '🛟',
  'Возможности для РОПа': '✨',
  'Вводный курс':         '🎓',
  'Частые вопросы':       '❓',
};

type Filter = 'Все' | string;

export function KnowledgePage({ favorites, onToggleFavorite, onOpenArticle }: Props) {
  const [query, setQuery] = useState('');
  const [activeCategory, setActiveCategory] = useState<Filter>('Все');
  const [activeSection, setActiveSection] = useState<Filter>('Все');
  const [showFavorites, setShowFavorites] = useState(false);

  const filtered = KNOWLEDGE_ARTICLES.filter(d => {
    const matchCat = activeCategory === 'Все' || d.category === activeCategory;
    const matchSec = activeSection === 'Все' || d.section === activeSection;
    const matchFav = !showFavorites || favorites.has(d.id);
    const matchQ = !query || d.title.toLowerCase().includes(query.toLowerCase()) || d.description.toLowerCase().includes(query.toLowerCase());
    return matchCat && matchSec && matchFav && matchQ;
  });

  return (
    <div className="max-w-5xl mx-auto px-6 py-8">
      <div className="mb-6">
        <h1 className="text-2xl font-semibold text-gray-900 mb-1">База знаний</h1>
        <p className="text-sm text-gray-500">Документы, шаблоны и регламенты для работы с образовательной программой</p>
      </div>

      {/* Search + favorites */}
      <div className="flex gap-3 mb-5">
        <div className="relative flex-1">
          <Search size={15} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-gray-400" />
          <input
            type="text"
            placeholder="Поиск по документам..."
            value={query}
            onChange={e => setQuery(e.target.value)}
            className="w-full pl-10 pr-4 py-2.5 text-sm border border-gray-200 rounded-xl bg-white focus:outline-none focus:ring-2 focus:ring-indigo-300 focus:border-indigo-300 transition-all"
          />
        </div>
        <button
          onClick={() => setShowFavorites(v => !v)}
          className={`flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-medium border transition-all ${
            showFavorites
              ? 'bg-amber-50 border-amber-200 text-amber-700'
              : 'bg-white border-gray-200 text-gray-600 hover:border-amber-300 hover:text-amber-600'
          }`}
        >
          <Star size={14} className={showFavorites ? 'fill-amber-400 text-amber-400' : ''} />
          Избранное
          {favorites.size > 0 && (
            <span className={`w-5 h-5 rounded-full text-[10px] font-bold flex items-center justify-center ${showFavorites ? 'bg-amber-500 text-white' : 'bg-gray-200 text-gray-600'}`}>
              {favorites.size}
            </span>
          )}
        </button>
      </div>

      {/* Section filter */}
      <div className="mb-4">
        <div className="text-[10px] font-semibold text-gray-400 uppercase tracking-wide mb-2">Разделы</div>
        <div className="flex flex-wrap gap-2">
          <button
            onClick={() => setActiveSection('Все')}
            className={`px-3.5 py-2 rounded-xl text-sm font-medium transition-all ${activeSection === 'Все' ? 'bg-gray-900 text-white' : 'bg-white border border-gray-200 text-gray-600 hover:border-gray-300'}`}
          >
            Все разделы
          </button>
          {KNOWLEDGE_SECTIONS.map(sec => (
            <button
              key={sec}
              onClick={() => setActiveSection(sec)}
              className={`flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-sm font-medium transition-all ${
                activeSection === sec
                  ? 'bg-indigo-600 text-white shadow-sm shadow-indigo-200'
                  : 'bg-white border border-gray-200 text-gray-600 hover:border-indigo-200 hover:text-indigo-600'
              }`}
            >
              <span>{SECTION_ICON[sec]}</span>
              {sec}
            </button>
          ))}
        </div>
      </div>

      {/* Category filter */}
      <div className="flex flex-wrap gap-2 mb-6">
        <button
          onClick={() => setActiveCategory('Все')}
          className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${activeCategory === 'Все' ? 'bg-gray-800 text-white' : 'bg-white border border-gray-200 text-gray-600 hover:border-gray-300'}`}
        >
          Все категории
        </button>
        {KNOWLEDGE_CATEGORIES.map(cat => (
          <button
            key={cat}
            onClick={() => setActiveCategory(cat)}
            className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${activeCategory === cat ? 'bg-gray-700 text-white' : `${CAT_COLOR[cat]} border border-transparent hover:opacity-80`}`}
          >
            {cat}
          </button>
        ))}
      </div>

      {/* Results */}
      {filtered.length === 0 ? (
        <div className="text-center py-20 text-gray-400">
          <BookOpen size={44} className="mx-auto mb-3 opacity-20" />
          <p className="text-sm font-medium mb-1">Документы не найдены</p>
          <p className="text-xs text-gray-400">Попробуйте изменить запрос или фильтры</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {filtered.map(doc => {
            const Icon = doc.icon;
            const iconCls = COLOR_MAP[doc.color] || COLOR_MAP.indigo;
            const isFav = favorites.has(doc.id);
            return (
              <div
                key={doc.id}
                className="bg-white rounded-2xl border border-gray-200 p-5 hover:shadow-lg hover:shadow-gray-100 hover:border-gray-300 transition-all group cursor-pointer flex flex-col"
                onClick={() => onOpenArticle(doc.id)}
              >
                <div className="flex items-start justify-between mb-3">
                  <div className={`w-11 h-11 rounded-xl border flex items-center justify-center ${iconCls}`}>
                    <Icon size={20} />
                  </div>
                  <div className="flex items-center gap-1.5">
                    <button
                      onClick={e => { e.stopPropagation(); onToggleFavorite(doc.id); }}
                      className={`w-7 h-7 rounded-lg flex items-center justify-center transition-all ${isFav ? 'text-amber-400' : 'text-gray-300 hover:text-amber-400 hover:bg-amber-50'}`}
                      title={isFav ? 'Убрать из избранного' : 'Добавить в избранное'}
                    >
                      <Star size={14} className={isFav ? 'fill-amber-400' : ''} />
                    </button>
                    <span className="text-[10px] font-bold text-gray-400 bg-gray-100 px-1.5 py-0.5 rounded">{doc.type}</span>
                  </div>
                </div>

                <h3 className="text-sm font-semibold text-gray-800 mb-1.5 leading-snug group-hover:text-indigo-700 transition-colors flex-1">{doc.title}</h3>
                <p className="text-xs text-gray-500 leading-relaxed mb-3 line-clamp-2">{doc.description}</p>

                <div className="flex items-center justify-between mt-auto pt-3 border-t border-gray-50">
                  <div className="flex items-center gap-1.5">
                    <span className={`text-[10px] font-semibold px-1.5 py-0.5 rounded-md ${CAT_COLOR[doc.category]}`}>{doc.category}</span>
                    <span className="text-[10px] text-gray-400">{doc.readTime}</span>
                  </div>
                  <span className="text-[10px] text-gray-400">Обновлён {doc.updated}</span>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}

// src/app/components/pages/KnowledgePage.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { Star, BookOpen } from 'lucide-vue-next'
import { KNOWLEDGE_ARTICLES } from '../../data/knowledge'

interface Props {
  searchQuery: string
  favorites: Set<string>
}

interface Emits {
  toggleFavorite: [id: string]
  openArticle: [id: string]
}

const props = defineProps<Props>()
const emit = defineEmits<Emits>()

const showFavoritesOnly = ref(false)

const favoriteCount = computed(() => props.favorites.size)

const normalizedSearch = computed(() => props.searchQuery.trim().toLowerCase())

const articles = computed(() => {
  const q = normalizedSearch.value
  return KNOWLEDGE_ARTICLES.filter((article) => {
    if (showFavoritesOnly.value && !props.favorites.has(article.id)) return false
    if (!q) return true

    return [
      article.title,
      article.description,
      article.category,
      article.section,
      article.type,
      article.summary,
      ...article.steps.flatMap((step) => [step.title, step.content]),
    ].some((value) => value.toLowerCase().includes(q))
  })
})

const getIconColor = (color: string) => {
  const colors: Record<string, string> = {
    'text-indigo-600': 'text-indigo-600',
    'text-emerald-600': 'text-emerald-600',
    'text-sky-600': 'text-sky-600',
    'text-orange-600': 'text-orange-600',
  }
  return colors[color] || 'text-indigo-600'
}
</script>

<template>
  <div class="max-w-5xl mx-auto px-6 py-8">
    <div class="mb-8 flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
      <div>
        <h1 class="text-3xl font-bold text-gray-900 mb-2">База знаний</h1>
        <p class="text-gray-600">Руководства, инструкции и справочная информация для руководителей образовательных программ</p>
      </div>
      <button
        @click="showFavoritesOnly = !showFavoritesOnly"
        :class="[
          'inline-flex items-center justify-center gap-2 self-start px-3.5 py-2 rounded-xl text-sm font-medium border transition-all',
          showFavoritesOnly
            ? 'bg-yellow-50 border-yellow-200 text-yellow-700 shadow-sm'
            : 'bg-white border-gray-200 text-gray-600 hover:border-yellow-200 hover:text-yellow-600',
        ]"
      >
        <Star :size="15" :fill="showFavoritesOnly ? 'currentColor' : 'none'" />
        Избранное
        <span
          :class="[
            'min-w-5 h-5 px-1.5 rounded-full text-[10px] flex items-center justify-center font-bold',
            showFavoritesOnly ? 'bg-yellow-200 text-yellow-800' : 'bg-gray-100 text-gray-500',
          ]"
        >
          {{ favoriteCount }}
        </span>
      </button>
    </div>

    <div
      v-if="articles.length === 0"
      class="text-center py-16 text-gray-400 bg-white rounded-2xl border border-gray-200"
    >
      <Star :size="40" class="mx-auto mb-3 opacity-30" />
      <p class="text-sm">
        {{ normalizedSearch ? 'Материалы по запросу не найдены' : 'В избранном пока нет материалов' }}
      </p>
    </div>

    <div v-else class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
      <button
        v-for="article in articles"
        :key="article.id"
        @click="emit('openArticle', article.id)"
        class="bg-white rounded-2xl border border-gray-200 p-5 hover:shadow-md transition-all text-left group"
      >
        <div class="flex items-start justify-between mb-3">
          <div :class="['w-10 h-10 rounded-lg bg-indigo-50 flex items-center justify-center', getIconColor(article.color)]">
            <BookOpen :size="18" />
          </div>
          <button
            @click.stop="emit('toggleFavorite', article.id)"
            class="text-gray-400 hover:text-yellow-500 transition-colors"
          >
            <Star :size="16" :fill="props.favorites.has(article.id) ? 'currentColor' : 'none'" />
          </button>
        </div>
        <h3 class="font-semibold text-gray-900 mb-1 group-hover:text-indigo-600 transition-colors">{{ article.title }}</h3>
        <p class="text-sm text-gray-600 line-clamp-2 mb-3">{{ article.description }}</p>
        <div class="flex items-center justify-between text-xs text-gray-500">
          <span class="bg-gray-100 px-2 py-1 rounded">{{ article.category }}</span>
          <span>{{ article.readTime }}</span>
        </div>
      </button>
    </div>
  </div>
</template>
